### ISSUE TITLE
Add pause command

### ISSUE THREAD

**Issue by Cephian** [anoadragon453/busty#107]
Especially with how long busts are getting, it might be a good idea to add a `!pause` and `!resume` command so we can implement a break

**Comment by anoadragon453** [comment]
The original purpose for this was to implement an intermission, but today we do this using audio submissions from busters. A further improvement would likely involve reordering the list of songs to insert that intermission submission in the middle, rather than using `!pause` and `!resume` commands.

It's also often unlikely that we'll see songs long enough for us to need to take a break in the middle of them. And if we want to stop in the middle of a bust for any reason, we'll likely start from the beginning of a song again. In which case we can use a combination of `!stop` and `!bust <song number>`.

So let's close this for now. We can re-open if we end up finding a use case.
