### ISSUE TITLE
Using `!list` during a bust will override and restart the current playlist

### ISSUE THREAD

**Issue by DipayanP007** [anoadragon453/busty#34]
I have found an issue:
* When audio is playing and if `!list` command is used, it shows the list of all audios scraped. But if `!skip` is used after `list` command, it starts playing audio from the top of the list rather than continuing from the present index.

#### Here are some screenshots:

![](https://github.com/DipayanP007/busty/blob/images/resource/7.png?raw=true)

![](https://github.com/DipayanP007/busty/blob/images/resource/9.png?raw=true)

**Comment by anoadragon453** [comment]
We should probably prevent `!skip` and `!stop` from working unless a bust is currently ongoing.

**Comment by anoadragon453** [comment]
Oh, I misread this. You mentioned that audio is playing.

Typically one should not run `!list` when audio is playing, but only beforehand. See [this explanation](https://github.com/anoadragon453/busty/blob/761a73894798b09a24519df70d3ca14ae7919868/README.md#usage) of how the bot is intended to be used.

The issue here occurs because `!list` will override the queue of songs with a new queue generated from the channel.

Typically one would never want to do this during playback, so the right thing to do here is probably to only allow `!list` to work if playback is not currently ongoing.
